### ISSUE TITLE
External Stylesheet

### ISSUE THREAD

**Issue by ghost** [vladfilipro/gulp-style-inject#5]
The src attribute or path option doesn't work with external URLs.

**Comment by stevenrtill** [comment]
Receiving the following error when trying to inject an external sheet from a local directory:

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: ERROR: Source file cannot be found.

**Comment by vladfilipro** [comment]
Support for external files will not be implemented. 

Since the merge with css is done at built time, external packages can be used to download remote css locally before using gulp-style-inject on them.
